# Generated by Django 6.0.5 on 2026-05-11 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('horario', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField()),
                ('plazas_disponibles', models.PositiveIntegerField()),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_impartidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'actividad')},
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuarios_inscritos',
            field=models.ManyToManyField(blank=True, related_name='actividades_inscritas', through='gestion.Inscripcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('responsable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='sala_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_principales', to='gestion.sala'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='salas_secundarias',
            field=models.ManyToManyField(blank=True, related_name='actividades_secundarias', to='gestion.sala'),
        ),
    ]
